### ISSUE TITLE
Ledger wallet migration with unknwon_error (0x6a81) at Sign Transactions step

### ISSUE THREAD

**Issue by Juweii** [helium/helium-program-library#204] opened 2023-04-24 18:21 UTC
Can anyone check the logs of the migration service on the server side when we try to migrate our wallet to Solana 44/501 using the migration tool?

![image](https://user-images.githubusercontent.com/5314938/234080229-d4cebd31-bf50-42de-98b5-90474fb0a0b7.png)

On Discord I found another user (grfx) with the exact same problem with the following similarities:

- Ledger Nano X
- FW: 2.1.0
- Ledger App Solana: 1.3.1
- Ledger App Helium-Solana: 1.3.0
- Hotspot(s) linked to the Ledger wallet

I also tried to use the Solana CLI for testing purposes and the following command works well with the Solana App, but not with the Helium-Solana app, although here only the derivation path has been changed compared to the Solana app:

Solana App open:
````
% solana-keygen pubkey "usb://ledger"
98pGRK*****************************FvGk1
````

Helium-Solana App open:
````
% solana-keygen pubkey "usb://ledger" 
Error: protocol error: Unknown error
````

Not sure if this has anything to say, but "Unkown error" is a match here. 🤓

Can any of you help to fix this problem so that we (with the setup above) can migrate?
Thanks in advance!

Juergen
Discord: Hawk#0416

**Comment by mandros1985** [comment] 2023-04-24 18:35
hello just like Hawk said. The exact same case - old helium ledger wallet has attached hotspots to it 

Possibly the root cause of the migration failing 

I have made inquiries regarding this long ago before the migration 

all of the discussion is on this link 

https://discord.com/channels/404106811252408320/743676367069249536/1100099584216268810 

old issue https://github.com/helium/helium-ledger-cli/issues/24

**Comment by ChewingGlass** [comment] 2023-04-25 19:37
You need to make sure you follow the instructions fully. Do not switch apps when not instructed to

**Comment by Juweii** [comment] 2023-04-25 19:48
It's not like trying once and crying, I tested this so many times on different browsers and even on different OS. And of course followed the instructions - it's not that easy. First open the Solana App, step 2 quit and open the Helium-Solana App and keep it open until finished.
Ledger live closed.
So nothing we could do wrong here.

I also tried to migrate account 1 (no hnt, iot or even Hotspot there) and I could fully complete the steps.

So I am pretty sure now, the issue is the linked Hotspot on account 0.

**Comment by ChewingGlass** [comment] 2023-04-25 22:39
kk trying to reproduce now

**Comment by mandros1985** [comment] 2023-04-26 08:32
Same on my side. Tried with different browsers incognito and normal 
installed and uninstalled solana apps on the ledger device, retried etc. 

Exact same output, exact same setup for soft and hardware 

In the old app (black helium wallet app on ios) there is only a option to look up what is going on on that wallet 

- no option to move funds etc 
- no option to claim rewards from connected hotspots 
- no option exept view 

help us please :(

**Comment by mandros1985** [comment] 2023-04-26 08:33
erratum 

- you can claim and it even says that it succeeded, but it dose not move the iot tokens to the wallet ballance 
- you can try 100 times individually to claim - tokens stay assigned to device anyway
- claim all dose not succeed it says "block size too big"

its a mess :(

**Comment by ChewingGlass** [comment] 2023-04-26 14:03
This should be fixed. Let me know if you still get this issue.

**Closed by ChewingGlass** 2023-04-26 14:03 UTC

**Comment by ChewingGlass** [comment] 2023-04-26 15:05
Guessing you have 4 or more hotspots on that wallet? Try again. Just pushed a fix @mandros1985

**Comment by jlacuisse** [comment] 2023-04-26 16:20
Hello, 
I have excatly the same problerme when i try to sign transaction in the helium-solana app unknwon_error (0x6a81).
I have an hotspot linked to my ledger. i try with a lot of sol on my ledger wallet but it is the same thing. i try with brave chrome
On windows, android.
it's very strange because i have the problem only with the account 0 with my hotspot.
But when i try with an other account (1 for example (i have nothin on them) ) i can sign transaction

**Comment by Juweii** [comment] 2023-04-26 16:26
Just tested right at the moment, still get the unknown_error:
<img width="845" alt="image" src="https://user-images.githubusercontent.com/5314938/234640803-935c740f-8728-4880-bc6b-b64789cdecb6.png">

**Comment by ChewingGlass** [comment] 2023-04-26 17:18
@Juweii Okay one more try, hit it again.

**Comment by mandros1985** [comment] 2023-04-26 18:34
@ChewingGlass IT WORKED !! 😉
I have successfully migrated to solana all of my assets
including connected nfts / miners
I can now see them in solflare

**Comment by Juweii** [comment] 2023-04-26 19:30
Finally, it worked.
But I received the transaction messages as "Unrecognized format". However I could finish the steps now.
![IMG_2904](https://user-images.githubusercontent.com/5314938/234682655-7b2b0d37-5079-4cc8-8bac-3146d05e0e3a.jpeg)

Thank you for your effort!

**Comment by mandros1985** [comment] 2023-04-26 19:37
Yes it did say that for each of my miners also when I moved them to another account later 

But Thanks again a milion for the support !

**Comment by Juweii** [comment] 2023-04-26 19:44
You moved the hotspots away from ledger? How?

**Comment by mandros1985** [comment] 2023-04-26 19:46
connect Your now migrated to solana ledger with solflare wallet and transfer the nft hotspots anywhere You want

**Comment by Juweii** [comment] 2023-04-26 19:54
Thank you
